"""add field tasks time_from

Revision ID: 3dfad49ffe16
Revises: e4549d617c70
Create Date: 2026-02-01 11:13:31.784384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfad49ffe16'
down_revision: Union[str, Sequence[str], None] = 'e4549d617c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_from', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('time_to', sa.String(), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('time_to')
        batch_op.drop_column('time_from')

    # ### end Alembic commands ###
