"""rename tasks

Revision ID: c01a35a8fcb4
Revises: e6bc99f137db
Create Date: 2026-01-27 19:36:35.712674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01a35a8fcb4'
down_revision: Union[str, Sequence[str], None] = 'e6bc99f137db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('task', sa.String(), nullable=False))
        batch_op.drop_column('content')
        batch_op.drop_column('task_time')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_time', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('task')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
